default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch('DB_USER', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', '-mlretro2019') %>
  host: <%= ENV.fetch('DB_HOST', 'db') %>

development:
  <<: *default
  database: ml-retro_development

test:
  <<: *default
  database: lw-retro_test

production:
  <<: *default
  database: lw-retro_production
